<a href="https://colab.research.google.com/github/ArpitAwasti/PyTorch/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Pytorch Fundamentals***

**Simple Array manipulation/creation**

In [ ]:
import torch
import numpy

# create tensor from numpy array
numpy_tensor = numpy.random.randn(2, 2)
numpy_tensor

array([[ 0.64719971, -0.55039169],
       [-1.04770163,  0.50044307]])

In [ ]:
# create tensor from pytorch tensor
pytorch_tensor = torch.randn(2, 2)
pytorch_tensor

tensor([[ 0.9466, -1.0621],
        [ 0.5698,  1.3731]])

In [ ]:
# convert numpy array to pytorch array
torch.Tensor(numpy_tensor)

tensor([[-0.5508,  0.4633],
        [-2.9321,  1.0613]])

In [ ]:
# or another way
torch.from_numpy(numpy_tensor)

tensor([[-0.3673, -0.6668],
        [ 1.3989,  0.3663]], dtype=torch.float64)

In [ ]:
# convert torch tensor to numpy representation
pytorch_tensor.numpy()

array([[ 0.94664496, -1.0621291 ],
       [ 0.5698473 ,  1.3730507 ]], dtype=float32)

In [ ]:
# create default arrays
torch.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
torch.rand(2, 2)

tensor([[0.4144, 0.8178],
        [0.4656, 0.2679]])

**Define manual seed**

In [ ]:
# CPU seed
torch.manual_seed(42)

# GPU seed
torch.cuda.manual_seed_all(42)

**Move tensor from GPU to CPU and back**

In [ ]:
# move to GPU
cpu_tensor.cuda()

# move to CPU
gpu_tensor.cpu()

**Tensor manipulations**

In [ ]:
a = torch.rand(2, 3)
a

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [ ]:
# get the shape of tensor
a.size()

torch.Size([2, 3])

In [ ]:
# reshape tensor to required shape
a.view(3, -1)

tensor([[0.7411, 0.4294],
        [0.8854, 0.5739],
        [0.2666, 0.6274]])

In [ ]:
# simple addition
b = torch.ones((2, 3))
c = a + b
c = torch.add(a, b)
c

tensor([[1.2566, 1.7936, 1.9408],
        [1.1332, 1.9346, 1.5936]])

In [ ]:
# in-place addition
a.add_(b)

tensor([[9.2566, 9.7936, 9.9408],
        [9.1332, 9.9346, 9.5936]])

In [ ]:
a

tensor([[9.2566, 9.7936, 9.9408],
        [9.1332, 9.9346, 9.5936]])

In [ ]:
# get the mean and std
a.mean(dim=1)
a.std(dim=0)

tensor([0.0872, 0.0997, 0.2455])

# ***Variable and Gradients***

**Variable Creation**

In [ ]:
from torch.autograd import Variable

# create variable
a = Variable(torch.ones((2, 3)), requires_grad=True)

# access variable tensor
a.data

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# access variable gradient
a.grad

**Compute Gradient**

In [ ]:
x = Variable(torch.ones(2), requires_grad=True)
y = 5 * (x + 2) ** 2

In [ ]:
# backward should be called only on a scalar
o = (1 / 2) * torch.sum(y)

In [ ]:
# compute backward
o.backward()

In [ ]:
# now we have the gradients of x
x.grad

tensor([15., 15.])